# Simplified Lab Configuration - Auto-Discovery Based
# Only contains journey definitions and optional section customizations
# Labs are automatically discovered from folders and README files

# =====================================================
# JOURNEY DEFINITIONS - Learning paths with metadata
# =====================================================
journeys:
  quick-start:
    title: "Quick Start Journey"
    description: "New to Copilot Studio? Start here with our essential labs to get up and running quickly."
    icon: "🚀"
    difficulty: "Beginner"
    estimated_time: "3-4 hours"
    
  business-user:
    title: "Business User Journey"
    description: "Perfect for business professionals who want to create powerful AI assistants without deep technical knowledge."
    icon: "💼"
    difficulty: "Beginner to Intermediate"
    estimated_time: "8-12 hours"
    
  developer:
    title: "Developer Journey"
    description: "Technical deep-dive into advanced features, integrations, and development best practices."
    icon: "🔧"
    difficulty: "Intermediate to Advanced"
    estimated_time: "10-15 hours"
    
  autonomous-ai:
    title: "Autonomous AI Journey"
    description: "Cutting-edge autonomous agents that can perform complex tasks with minimal human intervention."
    icon: "🤖"
    difficulty: "Advanced"
    estimated_time: "6-8 hours"

# =====================================================
# SECTION DEFINITIONS - Optional display customization
# =====================================================
sections:
  core_learning_path:
    title: "Core Learning Path"
    icon: "📚"
    slug: "core"
    type: "main"
    description: "Essential foundation labs - start here first!"
    
  intermediate_labs:
    title: "Intermediate Labs" 
    icon: "🎯"
    slug: "intermediate"
    type: "main"
    description: "Build on core concepts with practical applications"
    
  advanced_labs:
    title: "Advanced Labs"
    icon: "🚀"
    slug: "advanced"
    type: "main"
    description: "Complex scenarios and autonomous agents"
    
  specialized_labs:
    title: "Specialized Labs"
    icon: "⚡"
    slug: "specialized"
    type: "main"
    description: "Development tools and success measurement"
    
  optional_labs:
    title: "Optional Labs"
    icon: "🔧"
    slug: "optional"
    type: "optional"
    description: "Alternative versions and shorter formats"
    
  external_labs:
    title: "External Labs"
    icon: "🌐"
    slug: "external"
    type: "external"
    description: "Labs hosted in external repositories"

# =====================================================
# LAB ORDERING - Explicit order values for navigation
# =====================================================
lab_orders:
  # Core Learning Path (1-10)
  agent-builder-web: 1
  mbr-prep-sharepoint-agent: 2
  public-website-agent: 3
  standard-orchestrator: 4
  
  # Intermediate Labs (11-20)
  setup-for-success: 11
  agent-builder-sharepoint: 12
  ask-me-anything: 13
  
  # Advanced Labs (21-30)
  autonomous-cua: 21
  autonomous-account-news: 22
  autonomous-support-agent: 23
  
  # Specialized Labs (31-40)
  measure-success: 31
  pipelines-and-source-control: 32
  copilot-studio-kit: 33
  mcp-qualify-lead: 34
  
  # Optional Labs (41-50)
  ask-me-anything-30-mins: 41
  
  # External Labs (51-60)
  mcs-mcp-external: 51

# =====================================================
# LAB JOURNEY ASSIGNMENTS - Explicit journey mapping
# =====================================================
# This section provides explicit control over which journeys each lab belongs to.
# If a lab is listed here, it will use these exact journey assignments.
# If a lab is NOT listed here, the script will auto-assign journeys based on
# difficulty levels and content analysis (fallback behavior).
#
# Format: lab-folder-name: ["journey1", "journey2", ...]
# Available journeys: quick-start, business-user, developer, autonomous-ai
lab_journeys:
  # Core Learning Path - Foundation labs for everyone
  agent-builder-web: ["quick-start", "business-user"]
  mbr-prep-sharepoint-agent: ["quick-start", "business-user", "developer"]
  public-website-agent: ["quick-start", "business-user"]
  standard-orchestrator: ["quick-start", "developer"]
  
  # Intermediate Labs - Building on basics
  setup-for-success: ["business-user", "developer"]
  agent-builder-sharepoint: ["business-user", "developer"]
  ask-me-anything: ["business-user", "developer"]
  
  # Advanced Labs - Complex scenarios
  autonomous-cua: ["autonomous-ai", "developer"]
  autonomous-account-news: ["autonomous-ai", "developer"]
  autonomous-support-agent: ["autonomous-ai", "developer"]
  
  # Specialized Labs - Technical depth
  measure-success: ["developer"]
  pipelines-and-source-control: ["developer"]
  copilot-studio-kit: ["developer"]
  mcp-qualify-lead: ["developer"]
  
  # Optional Labs - Alternative approaches
  ask-me-anything-30-mins: ["business-user"]
  
  # External Labs - External repositories
  mcs-mcp-external: ["developer"]

# =====================================================
# EXTERNAL LABS - Labs not hosted in this repository
# =====================================================
external_labs:
  - id: mcs-mcp-external
    title: "Model Context Protocol (MCP) & Copilot Studio"
    duration: 90
    difficulty: "Advanced"
    description: "Learn to deploy an MCP Server and integrate it with Microsoft Copilot Studio"
    url: "https://github.com/microsoft/mcsmcp"
    repository: "microsoft/mcsmcp"
    journeys: ["developer"]

# =====================================================
# AUTO-DISCOVERY RULES (Optional - for documentation)
# =====================================================
# The system automatically:
# 1. Scans labs/ folders for README.md files
# 2. Extracts metadata from lab details tables
# 3. Auto-assigns sections based on:
#    - Difficulty levels (100=core, 200=intermediate, 300+=advanced)
#    - Folder name patterns (autonomous=advanced, 30-mins=optional, etc.)
# 4. Auto-assigns journeys based on:
#    - Difficulty and content analysis
#    - Keywords in titles and descriptions
# 5. Uses intelligent defaults for missing metadata

# To override auto-assignment, add YAML front matter to lab README files:
# ---
# journeys: ["custom-journey"]
# section: "custom_section"
# difficulty: 150
# duration: 45
# ---# Force trigger
