name: Enhancement
description: Suggest a general improvement to the bootcamp, site, or overall experience
labels: ["type: enhancement", "status: triage"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: What should change and why?
      description: Describe the enhancement you'd like to see
    validations:
      required: true
  - type: textarea
    id: attachment
    attributes:
      label: Supporting Material
      description: >-
        Drag and drop or paste a file (e.g., PowerPoint presentation) containing
        supporting material. GitHub supports attaching files up to 25 MB. For
        larger files, upload to SharePoint or OneDrive and paste the sharing link
        here instead.
      placeholder: Drag and drop your file here
    validations:
      required: false
