name: Deploy Jekyll Lab Browser

on:
  push:
    branches: [ main, feature/jekyll-lab-browser ]
    paths: [ 'labs/**', '_layouts/**', 'assets/**', '_config.yml', 'index.md', 'convert-labs.sh' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Convert labs to Jekyll format
        run: |
          chmod +x convert-labs.sh
          ./convert-labs.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install Jekyll dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --verbose
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4